version: '3'

services:

  postgresd:
    container_name: frame_postgres
    image: postgres:14
    environment:
      - POSTGRES_USER=frame
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=framedatabase
    ports:
      - 5423:5432

  keto-migrate:
    container_name: frame_keto_migration
    image: oryd/keto:latest
    links:
      - postgresd:postgresd
    depends_on:
      - postgresd
    environment:
      - LOG_LEVEL=debug
    command:
      migrate up --yes
    restart: on-failure
    volumes:
      - ./keto.yaml:/home/ory/keto.yml

  keto:
    container_name: frame_keto
    image: oryd/keto:latest
    links:
      - postgresd:postgresd
    depends_on:
      - postgresd
      - keto-migrate
    volumes:
      - ./keto.yaml:/home/ory/keto.yml
    ports:
      - 4466:4466
      - 4467:4467
      
