name: Test

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.19'
      - name: Build the docker-compose stack
        run: docker-compose -f tests_runner/docker-compose.yml up -d
      - name: Wait for afew seconds
        run: sleep 5
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker-compose -f ./tests_runner/docker-compose.yml logs
      - name: Run test suite
        run: go test -v ./...