name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      PG_PASS: ${{ secrets.PG_PASS }}
      DATABASE_URL: postgresql://postgres:${{ secrets.SECRET_PASSWORD }}@postgres/postgres
      DJANGO_SETTINGS_MODULE: app_name.settings.dev
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      PORT: 8000

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Build the docker-compose stack
        run: docker-compose -f tests_runner/docker-compose.yml up -d
      - name: Wait for afew seconds
        run: sleep 5
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker-compose -f ./tests_runner/docker-compose.yml logs
      - name: Run test suite
        run: go test -v ./...